spring:
  profiles:
    active: -dev

---
server.port: 8000
spring:
  profiles: dev #开发环境
  application:
    name: microservice-client-remote-dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
---
server.port: 8001
spring:
  profiles: test
  application:
    name: microservice-client-remote-test
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
      
      
